SELECT
    ''                         AS "Anrede",
    c."firstName"              AS "Vorname",
    ''                         AS "Weitere Vornamen",
    c."lastName"               AS "Nachname",
    ''                         AS "Suffix",
    a."name1"                  AS "Firma",
    a."name2"                  AS "Abteilung",
    c."functionName"           AS "Position",
    ''                         AS "Straße geschäftlich",
    ''                         AS "Straße geschäftlich 2",
    ''                         AS "Straße geschäftlich 3",
    ''                         AS "Ort geschäftlich",
    ''                         AS "Region geschäftlich",
    ''                         AS "Postleitzahl geschäftlich",
    ''                         AS "Land/Region geschäftlich",
    ''                         AS "Straße privat",
    ''                         AS "Straße privat 2",
    ''                         AS "Straße privat 3",
    ''                         AS "Ort privat",
    ''                         AS "Bundesland/Kanton privat",
    ''                         AS "Postleitzahl privat",
    ''                         AS "Land/Region privat",
    ''                         AS "Weitere Straße",
    ''                         AS "Weitere Straße 2",
    ''                         AS "Weitere Straße 3",
    ''                         AS "Weiterer Ort",
    ''                         AS "Weiteres/r Bundesland/Kanton",
    ''                         AS "Weitere Postleitzahl",
    ''                         AS "Weiteres/e Land/Region",
    ''                         AS "Telefon Assistent",
    c."fax"                    AS "Fax geschäftlich",
    c."phone1"                 AS "Telefon geschäftlich",
    c."phone2"                 AS "Telefon geschäftlich 2",
    ''                         AS "Rückmeldung",
    ''                         AS "Autotelefon",
    ''                         AS "Telefon Firma",
    ''                         AS "Fax privat",
    ''                         AS "Telefon (privat)",
    ''                         AS "Telefon (privat 2)",
    ''                         AS "ISDN",
    c."mobile1"                AS "Mobiltelefon",
    ''                         AS "Weiteres Fax",
    c."phone3"                 AS "Weiteres Telefon",
    ''                         AS "Pager",
    ''                         AS "Haupttelefon",
    c."mobile2"                AS "Mobiltelefon 2",
    ''                         AS "Telefon für Hörbehinderte",
    ''                         AS "Telex",
    ''                         AS "Abrechnungsinformation",
    ''                         AS "Assistent(in)",
    ''                         AS "Benutzer 1",
    ''                         AS "Benutzer 2",
    ''                         AS "Benutzer 3",
    ''                         AS "Benutzer 4",
    ''                         AS "Beruf",
    ''                         AS "Büro",
    ''                         AS "E-Mail-Adresse",
    ''                         AS "E-Mail-Typ",
    ''                         AS "E-Mail: Angezeigter Name",
    ''                         AS "E-Mail 2: Adresse",
    ''                         AS "E-Mail 2: Typ",
    ''                         AS "E-Mail 2: Angezeigter Name",
    ''                         AS "E-Mail 3: Adresse",
    ''                         AS "E-Mail 3: Typ",
    ''                         AS "E-Mail 3: Angezeigter Name",
    ''                         AS "Empfohlen von",
    ''                         AS "Geburtstag",
    ''                         AS "Geschlecht",
    ''                         AS "Hobby",
    ''                         AS "Initialen",
    ''                         AS "Internet Frei/Gebucht",
    ''                         AS "Jahrestag",
    ''                         AS "Kategorien",
    ''                         AS "Kinder",
    ''                         AS "Konto",
    ''                         AS "Name des/r Vorgesetzten",
    ''                         AS "Notizen",
    ''                         AS "Organisationsnr.",
    ''                         AS "Ort",
    ''                         AS "Partner",
    ''                         AS "Postfach geschäftlich",
    ''                         AS "Postfach privat",
    ''                         AS "Priorität",
    ''                         AS "Privat",
    ''                         AS "Reisekilometer",
    ''                         AS "Sozialversicherungsnr.",
    ''                         AS "Sprache",
    a."name3"                  AS "Stichwörter",
    ''                         AS "Vertraulichkeit",
    ''                         AS "Verzeichnisserver",
    ''                         AS "Webseite",
    ''                         AS "Weiteres Postfach",
    ''                         AS "Spalte1",
    ''                         AS "Spalte2"
FROM public.contacts c
LEFT JOIN public.addresses a
       ON c."addressId" = a.id
WHERE c."exportFlag" IS TRUE
ORDER BY c.id ASC;